export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const GET_ALL_PRODUCTS_CATEGORY = 'GET_ALL_PRODUCTS_CATEGORY';
export const GET_ALL_COLORS = 'GET_ALL_COLORS';
export const GET_ALL_BLOGS = 'GET_ALL_BLOGS';
